### ISSUE TITLE
Add support for Yacht Devices NMEA2000 Wifi gateway

### ISSUE THREAD

**Issue by jncarter123** [canboat/canboatjs#42]
[ydwg-2000.log](https://github.com/canboat/canboatjs/files/2873170/ydwg-2000.log)
It would be great to add support for the Yacht Devices NMEA 2000 WIFI gateway. I've attached a copy of the raw data log. Information on the data format can be found at http://www.yachtd.com/downloads/ydwg02.pdf Appendix E pg 55. I'd be happy to help how I can. Thank you!

**Comment by webmasterkai** [comment]
I have a YDWG in the mail and am hoping it shows up soon. I've installed a couple on client boats and ended up liking them way more than I thought.

I'd like to see some of the canboatjs code split between the serial port connections and the actual parsing of binary data so that it's easier to add support for any kind of data feed. Ideally the parsing of binary data could be its own package and also accept a list of PGN information from an outside source.
